### PR TITLE
fix QA issue by adding bash to RDEPENDS

### PR DESCRIPTION
**Pull request by mPorst**
Was unable to build fwup out of the box but the fix is trivial.

### CODE REVIEW

**Comment by fhunleth** [comment]
I don't use Yocto, but isn't RDEPENDS for runtime dependencies? `fwup` shouldn't need `bash` or any shell at runtine. Maybe bitbake is smart and detecting the helper scripts? If that's the case, then passing `--disable-scripts` to `./configure` should prevent them from being installed. They're not needed on the target.

**Comment by mPorst** [comment]
Hello,

 

Yes RDEPENDS are runtime dependencies. I am also not a power user of yocto, I just stumbled upon this error and since bitbake suggested to add this "rdepends" I tried it and it worked.

In your fwup_git.bb file it reads the following 3 lines:

 


FILES_${PN} += "${datadir}/bash-completion/completions/fwup \
               ${bindir}/fwup \
"

I don't know where to find this file but judging from the directory it pulls in bash dependencies.

 

Best regards

Moritz

 


 

Gesendet: Montag, 27. Mai 2019 um 13:44 Uhr
Von: "Frank Hunleth" <notifications@github.com>
An: fhunleth/meta-fwup <meta-fwup@noreply.github.com>
Cc: Moritz <moritz.porst@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [fhunleth/meta-fwup] fix QA issue by adding bash to RDEPENDS (#4)


I don't use Yocto, but isn't RDEPENDS for runtime dependencies? fwup shouldn't need bash or any shell at runtine. Maybe bitbake is smart and detecting the helper scripts? If that's the case, then passing --disable-scripts to ./configure should prevent them from being installed. They're not needed on the target.

**Comment by fhunleth** [comment]
The bash completions are definitely not need on the target either. Those should not be installed. Those can be skipped by passing a flag to configure as well.

**Comment by michaelkschmidt** [comment]
I forgot to create a PR for the fix for this.  Its commit is here: 

https://github.com/se-apc/meta-fwup/commit/63cf80b664941c1aedf6d0195f8f007527625a5c

@fhunleth do you want fwup to point to true releases?  Or are SHAs ok?  I will create a PR

@mPorst we can't have a runtime dependency on bash bc most people ship with just busy box's `/bin/sh`

Also, @mPorst are you using Nerves with Yocto?  There is a port here: https://github.com/se-apc/nerves_system_yocto

I need to document it better but its definitely working.  I would be glad to help you get going if it is of interest

**Comment by fhunleth** [comment]
I prefer real releases if possible.

**Comment by michaelkschmidt** [comment]
@mPorst See if #5 works for you.

**Comment by mPorst** [comment]
I can only test this on friday since I am on part time. But I will report back. Thanks !
Best regards

// and no, I don't use nerves
// closing the PR for now, will answer under #5

**Pull request closed without merging**
