### PR TITLE
Bump to version 1.2.6

### PR DESCRIPTION
**Pull request by michaelkschmidt**
Sync to latest release

### CODE REVIEW

**Comment by fhunleth** [comment]
There's a merge conflict. I thought this would be easy, but enough changed that it really needs testing. Could you take a look?

**Comment by michaelkschmidt** [comment]
Oops I missed that.  let me retest real quick

**Comment by michaelkschmidt** [comment]
I switched it to use the git repo for building.  This makes updates easier bc you only have to change the SHA of the commit and the version number

**Comment by fhunleth** [comment]
Merged. Thanks!

**Pull request closed without merging**
